// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYk7I3BtVdV-BRfN3znGM3qUckRedy7UI',
    appId: '1:714626395898:web:260f613cb54fe7b54b2343',
    messagingSenderId: '714626395898',
    projectId: 'smartinventory-51751',
    authDomain: 'smartinventory-51751.firebaseapp.com',
    storageBucket: 'smartinventory-51751.appspot.com',
    measurementId: 'G-XJHW0Y1CL2',
    databaseURL: 'https://smartinventory-51751-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Y68lJFLeAFYF53gc7pP7IWKN4frQ26M',
    appId: '1:714626395898:android:c2d930fac9c0b3b14b2343',
    messagingSenderId: '714626395898',
    projectId: 'smartinventory-51751',
    storageBucket: 'smartinventory-51751.appspot.com',
    databaseURL: 'https://smartinventory-51751-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNxvk0axhw-3IZ9SnkGk0OFHH6v6fdZD8',
    appId: '1:714626395898:ios:4bf1ca1dcef458c84b2343',
    messagingSenderId: '714626395898',
    projectId: 'smartinventory-51751',
    storageBucket: 'smartinventory-51751.appspot.com',
    iosBundleId: 'com.example.smartinventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNxvk0axhw-3IZ9SnkGk0OFHH6v6fdZD8',
    appId: '1:714626395898:ios:656be5651803b8a04b2343',
    messagingSenderId: '714626395898',
    projectId: 'smartinventory-51751',
    storageBucket: 'smartinventory-51751.appspot.com',
    iosBundleId: 'com.example.smartinventory.RunnerTests',
  );
}
